#ODMD 329d4bdadaff2a84daf3212e845dedcbf368621d GENERATED WORKFLOW, don't change unless you are sure.

name: ODMD_ragStore-CdkGithubWFus-east-2-workspace2
on:
  workflow_dispatch:
    inputs:
      message:
        type: string
        required: false
        default: ''
        description: 'additional message'
jobs:
  odmd_job:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: 'arn:aws:iam::217471730138:role/ragStore/ragStore-us-east-2217471730138-buildRole'
          aws-region: us-east-2

      - uses: ondemandenv/wflact-resolvEnvars@odmd-rag
        with:
          aws_credentials: ${{github.event.inputs.aws_credentials}}
          trigger_message: ${{github.event.inputs.message}}
        env:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          ODMD_buildId: ragStore
          ODMD_awsRegion: us-east-2
          ODMD_SECRETS: ${{ secrets['ODMD_SECRETS_ODMD_ragStore_CdkGithubWFus_east_2_workspace2'] }}
      
      - name: run enver local script
        run: |
          set -ex
          
          if [[ -n "${{ env.ODMD_work_dir }}" ]]; then
            cd "${{ env.ODMD_work_dir }}"
          else
            echo "ODMD_work_dir is empty, staying in current directory"
            ls -ltarh
          fi
          
          pwd
          env | grep -i ^ODMD
          
          if [ -f ${{ env.ODMD_buildScript }} ]; then
            chmod +x ${{ env.ODMD_buildScript }}
            ./${{ env.ODMD_buildScript }}
          else
            echo "${{ env.ODMD_buildScript }} does not exist, continue ..."
          fi
          
        env:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          ODMD_buildId: ragStore
          ODMD_SECRETS: ${{ secrets['ODMD_SECRETS_ODMD_ragStore_CdkGithubWFus_east_2_workspace2'] }}      
          
      - uses: ondemandenv/wflact-buildProduces@odmd-rag
        env:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          ODMD_buildId: ragStore
          ODMD_SECRETS: ${{ secrets['ODMD_SECRETS_ODMD_ragStore_CdkGithubWFus_east_2_workspace2'] }}

#